From python:3.8

WORKDIR /app
RUN apt-get update
RUN pip install --upgrade pip
COPY requirments_pip.txt /app/
RUN pip install --no-cache-dir -r requirments_pip.txt


RUN python3 -m spacy download en_core_web_sm
RUN python3 -m spacy download xx_ent_wiki_sm


COPY . /app/


CMD [ "python", "init_script.py"]
