version: '3.5'
networks:
    kafka:
      name: rmoff_kafka
      external: True
services:
  
  dataingest:
    build: ./dataingestService
    command: ["python","-u","auto_script.py"]
    networks:
      - kafka
     
  
      
  datastorage:    
    build: ./storageService
    command: ["python","-u","auto_script.py"]

    networks:
      - kafka  
       
    environment : 
        DB_HOST : postgres
        DB_PORT: 5432  
    depends_on:
      - postgres
      