version: '3.5'
networks:
    kafka:
      name: rmoff_kafka
      external: True
services:
  
  dataingest:
    build: ./dataingestService
    networks:
      - kafka
    

  
      
  datastorage:    
    build: ./storageService
    networks:
      - kafka  
       
    environment : 
        DB_HOST : postgres
        DB_PORT: 5432  
    
      

