version: '3.5'
networks:
    kafka:
      name: rmoff_kafka
      external: True
services:
  postgres:
      image: postgres:13
      networks:
      - kafka
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: airflow_user
        POSTGRES_PASSWORD: airflow_pass
      volumes:
      - ./data:/var/lib/postgresql/data  
      
      ports:
        - 5432:5432
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    container_name: zookeeper
    networks: 
      - kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    restart: always   
  

  broker:
    image: confluentinc/cp-kafka:5.5.0
    container_name: broker
    networks: 
      - kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    restart: always 

  web:
    build: ./Django
    ports:
      - "8000:8000"
    volumes:
      - .:/app   
    networks: 
      - kafka
    environment : 
      reception_api: reception_api  
      emission_api : emission_api    
        
        