From python:3.8

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requierment.txt /app/
RUN pip install --no-cache-dir -r requierment.txt
RUN pip install django

COPY . /app/

EXPOSE 8000

CMD ["python","Django/Api_setting/manage.py", "runserver", "0.0.0.0:8000" ]